logging:
  logs:
    default:
      level: DEBUG

apps:
  layer4:
    servers:
      http:
        listen: [":80"]
        routes:
          - match:
              - http: []
            handle:
              - handler: proxy
                upstreams:
                  - dial:
                      - "{l4.http.host}:80"

      https:
        listen: [":443"]
        routes:
          - match:
              - tls: {}
            handle:
              - handler: proxy
                upstreams:
                  - dial:
                      - "{l4.tls.server_name}:443"
