logging:
  logs:
    default:
      level: DEBUG

apps:
  layer4:
    servers:
      echotls:
        listen:
          - ":5020"
        routes:
          - handle:
              - handler: tls
              - handler: echo

      http:
        listen:
          - ":80"
        routes:
          - match:
              - http: []
            handle:
              - handler: proxy
                upstreams:
                  - dial:
                      - "{l4.http.host}:80"

      https:
        listen:
         - ":443"
        routes:
          - match:
              - tls: {}
            handle:
              - handler: tls
              - handler: proxy
                upstreams:
                  - dial:
                      - "{l4.tls.server_name}:443"
                    tls: {}

  tls:
    certificates:
      automate:
        - "*"
    automation:
      policies:
        - on_demand: true
          issuers:
            - module: internal
