apps:
  layer4:
    servers:
      srv0http:
        listen: [":80"]
        routes:
          - match:
              - http: []
            handle:
              - handler: proxy
                upstreams:
                  - dial:
                    - 127.0.0.1:8080
      srv0https:
        listen: [":443"]
        routes:
          - match:
              - tls: {}
            handle:
              - handler: proxy
                upstreams:
                  - dial:
                    - 127.0.0.1:8080
  http:
    servers:
      srv1:
        listen: [127.0.0.1:8080]
        routes:
          - handle:
            - handler: forward_proxy
              hide_ip: true
              hide_via: true
